library(conflicted)

# Resolve all conflicts
conflict_prefer("select",          "dplyr")
conflict_prefer("filter",          "dplyr")
conflict_prefer("lag",             "dplyr")
conflict_prefer("box",             "shinydashboard")
conflict_prefer("dataTableOutput", "DT")
conflict_prefer("renderDataTable", "DT")
conflict_prefer("layout",          "plotly")
conflict_prefer("as_data_frame",   "igraph")
conflict_prefer("union",           "igraph")
conflict_prefer("compose",         "igraph")
conflict_prefer("crossing",        "igraph")
conflict_prefer("decompose",       "igraph")
conflict_prefer("simplify",        "igraph")
conflict_prefer("spectrum",        "igraph")
conflict_prefer("%--%",            "igraph")
conflict_prefer("now",             "simmer")
conflict_prefer("reset",           "simmer")
conflict_prefer("rollback",        "simmer")
conflict_prefer("separate",        "simmer")
conflict_prefer("removeClass",     "shinyjs")
conflict_prefer("show",            "shinyjs")
conflict_prefer("runExample",      "shinyjs")
conflict_prefer("smiths",          "tidyr")
conflict_prefer("col_factor",      "readr")
conflict_prefer("discard",         "purrr")
conflict_prefer("viridis_pal",     "scales")
conflict_prefer("JS",              "DT")
conflict_prefer("page",            "bslib")

# All libraries (union of server.R + ui.R)
library(shiny)
library(simmer)
library(stringr)
library(stringi)
library(forcats)
library(tidyr)
library(ggplot2)
library(readr)
library(DT)
library(plotly)
library(sf)
library(scales)
library(shinyjs)
library(shinyFeedback)
library(shinydashboard)
library(shinyBS)
library(bslib)
library(reshape2)
library(igraph)
library(RColorBrewer)
library(dplyr)  # last so it wins by default